/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PriceHistoryRouteImport } from './routes/price-history'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FirstScanRouteImport } from './routes/first-scan'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CameraPermissionsRouteImport } from './routes/camera-permissions'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketIndexRouteImport } from './routes/market.index'
import { Route as CollectionIndexRouteImport } from './routes/collection.index'
import { Route as SellerNameRouteImport } from './routes/seller.$name'
import { Route as MessagesThreadIdRouteImport } from './routes/messages.$threadId'
import { Route as MarketMyListingsRouteImport } from './routes/market.my-listings'
import { Route as MarketListingIdRouteImport } from './routes/market.$listingId'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalAboutRouteImport } from './routes/legal.about'
import { Route as CollectionIdRouteImport } from './routes/collection.$id'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CheckoutFailedRouteImport } from './routes/checkout.failed'
import { Route as CertificateScanIdRouteImport } from './routes/certificate.$scanId'
import { Route as ScanSuccessScanIdRouteImport } from './routes/scan.success.$scanId'
import { Route as ScanResultScanIdRouteImport } from './routes/scan.result.$scanId'
import { Route as ScanFailedScanIdRouteImport } from './routes/scan.failed.$scanId'
import { Route as MarketPublishScanIdRouteImport } from './routes/market.publish.$scanId'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceHistoryRoute = PriceHistoryRouteImport.update({
  id: '/price-history',
  path: '/price-history',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstScanRoute = FirstScanRouteImport.update({
  id: '/first-scan',
  path: '/first-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraPermissionsRoute = CameraPermissionsRouteImport.update({
  id: '/camera-permissions',
  path: '/camera-permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketIndexRoute = MarketIndexRouteImport.update({
  id: '/market/',
  path: '/market/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionIndexRoute = CollectionIndexRouteImport.update({
  id: '/collection/',
  path: '/collection/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerNameRoute = SellerNameRouteImport.update({
  id: '/seller/$name',
  path: '/seller/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesThreadIdRoute = MessagesThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => MessagesRoute,
} as any)
const MarketMyListingsRoute = MarketMyListingsRouteImport.update({
  id: '/market/my-listings',
  path: '/market/my-listings',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketListingIdRoute = MarketListingIdRouteImport.update({
  id: '/market/$listingId',
  path: '/market/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAboutRoute = LegalAboutRouteImport.update({
  id: '/legal/about',
  path: '/legal/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionIdRoute = CollectionIdRouteImport.update({
  id: '/collection/$id',
  path: '/collection/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutFailedRoute = CheckoutFailedRouteImport.update({
  id: '/failed',
  path: '/failed',
  getParentRoute: () => CheckoutRoute,
} as any)
const CertificateScanIdRoute = CertificateScanIdRouteImport.update({
  id: '/certificate/$scanId',
  path: '/certificate/$scanId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanSuccessScanIdRoute = ScanSuccessScanIdRouteImport.update({
  id: '/success/$scanId',
  path: '/success/$scanId',
  getParentRoute: () => ScanRoute,
} as any)
const ScanResultScanIdRoute = ScanResultScanIdRouteImport.update({
  id: '/result/$scanId',
  path: '/result/$scanId',
  getParentRoute: () => ScanRoute,
} as any)
const ScanFailedScanIdRoute = ScanFailedScanIdRouteImport.update({
  id: '/failed/$scanId',
  path: '/failed/$scanId',
  getParentRoute: () => ScanRoute,
} as any)
const MarketPublishScanIdRoute = MarketPublishScanIdRouteImport.update({
  id: '/market/publish/$scanId',
  path: '/market/publish/$scanId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/billing': typeof BillingRoute
  '/camera-permissions': typeof CameraPermissionsRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/first-scan': typeof FirstScanRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/offline': typeof OfflineRoute
  '/onboarding': typeof OnboardingRoute
  '/premium': typeof PremiumRoute
  '/price-history': typeof PriceHistoryRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/wallet': typeof WalletRoute
  '/certificate/$scanId': typeof CertificateScanIdRoute
  '/checkout/failed': typeof CheckoutFailedRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/collection/$id': typeof CollectionIdRoute
  '/legal/about': typeof LegalAboutRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/market/$listingId': typeof MarketListingIdRoute
  '/market/my-listings': typeof MarketMyListingsRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/seller/$name': typeof SellerNameRoute
  '/collection/': typeof CollectionIndexRoute
  '/market/': typeof MarketIndexRoute
  '/market/publish/$scanId': typeof MarketPublishScanIdRoute
  '/scan/failed/$scanId': typeof ScanFailedScanIdRoute
  '/scan/result/$scanId': typeof ScanResultScanIdRoute
  '/scan/success/$scanId': typeof ScanSuccessScanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/billing': typeof BillingRoute
  '/camera-permissions': typeof CameraPermissionsRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/first-scan': typeof FirstScanRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/offline': typeof OfflineRoute
  '/onboarding': typeof OnboardingRoute
  '/premium': typeof PremiumRoute
  '/price-history': typeof PriceHistoryRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/wallet': typeof WalletRoute
  '/certificate/$scanId': typeof CertificateScanIdRoute
  '/checkout/failed': typeof CheckoutFailedRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/collection/$id': typeof CollectionIdRoute
  '/legal/about': typeof LegalAboutRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/market/$listingId': typeof MarketListingIdRoute
  '/market/my-listings': typeof MarketMyListingsRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/seller/$name': typeof SellerNameRoute
  '/collection': typeof CollectionIndexRoute
  '/market': typeof MarketIndexRoute
  '/market/publish/$scanId': typeof MarketPublishScanIdRoute
  '/scan/failed/$scanId': typeof ScanFailedScanIdRoute
  '/scan/result/$scanId': typeof ScanResultScanIdRoute
  '/scan/success/$scanId': typeof ScanSuccessScanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/billing': typeof BillingRoute
  '/camera-permissions': typeof CameraPermissionsRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/first-scan': typeof FirstScanRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/offline': typeof OfflineRoute
  '/onboarding': typeof OnboardingRoute
  '/premium': typeof PremiumRoute
  '/price-history': typeof PriceHistoryRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/wallet': typeof WalletRoute
  '/certificate/$scanId': typeof CertificateScanIdRoute
  '/checkout/failed': typeof CheckoutFailedRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/collection/$id': typeof CollectionIdRoute
  '/legal/about': typeof LegalAboutRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/market/$listingId': typeof MarketListingIdRoute
  '/market/my-listings': typeof MarketMyListingsRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/seller/$name': typeof SellerNameRoute
  '/collection/': typeof CollectionIndexRoute
  '/market/': typeof MarketIndexRoute
  '/market/publish/$scanId': typeof MarketPublishScanIdRoute
  '/scan/failed/$scanId': typeof ScanFailedScanIdRoute
  '/scan/result/$scanId': typeof ScanResultScanIdRoute
  '/scan/success/$scanId': typeof ScanSuccessScanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/billing'
    | '/camera-permissions'
    | '/checkout'
    | '/compare'
    | '/dashboard'
    | '/favorites'
    | '/first-scan'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/offline'
    | '/onboarding'
    | '/premium'
    | '/price-history'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/scan'
    | '/search'
    | '/settings'
    | '/stats'
    | '/verify-otp'
    | '/wallet'
    | '/certificate/$scanId'
    | '/checkout/failed'
    | '/checkout/success'
    | '/collection/$id'
    | '/legal/about'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/market/$listingId'
    | '/market/my-listings'
    | '/messages/$threadId'
    | '/seller/$name'
    | '/collection/'
    | '/market/'
    | '/market/publish/$scanId'
    | '/scan/failed/$scanId'
    | '/scan/result/$scanId'
    | '/scan/success/$scanId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/billing'
    | '/camera-permissions'
    | '/checkout'
    | '/compare'
    | '/dashboard'
    | '/favorites'
    | '/first-scan'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/offline'
    | '/onboarding'
    | '/premium'
    | '/price-history'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/scan'
    | '/search'
    | '/settings'
    | '/stats'
    | '/verify-otp'
    | '/wallet'
    | '/certificate/$scanId'
    | '/checkout/failed'
    | '/checkout/success'
    | '/collection/$id'
    | '/legal/about'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/market/$listingId'
    | '/market/my-listings'
    | '/messages/$threadId'
    | '/seller/$name'
    | '/collection'
    | '/market'
    | '/market/publish/$scanId'
    | '/scan/failed/$scanId'
    | '/scan/result/$scanId'
    | '/scan/success/$scanId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/billing'
    | '/camera-permissions'
    | '/checkout'
    | '/compare'
    | '/dashboard'
    | '/favorites'
    | '/first-scan'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/offline'
    | '/onboarding'
    | '/premium'
    | '/price-history'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/scan'
    | '/search'
    | '/settings'
    | '/stats'
    | '/verify-otp'
    | '/wallet'
    | '/certificate/$scanId'
    | '/checkout/failed'
    | '/checkout/success'
    | '/collection/$id'
    | '/legal/about'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/market/$listingId'
    | '/market/my-listings'
    | '/messages/$threadId'
    | '/seller/$name'
    | '/collection/'
    | '/market/'
    | '/market/publish/$scanId'
    | '/scan/failed/$scanId'
    | '/scan/result/$scanId'
    | '/scan/success/$scanId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BillingRoute: typeof BillingRoute
  CameraPermissionsRoute: typeof CameraPermissionsRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRoute
  FavoritesRoute: typeof FavoritesRoute
  FirstScanRoute: typeof FirstScanRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  OfflineRoute: typeof OfflineRoute
  OnboardingRoute: typeof OnboardingRoute
  PremiumRoute: typeof PremiumRoute
  PriceHistoryRoute: typeof PriceHistoryRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScanRoute: typeof ScanRouteWithChildren
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  WalletRoute: typeof WalletRoute
  CertificateScanIdRoute: typeof CertificateScanIdRoute
  CollectionIdRoute: typeof CollectionIdRoute
  LegalAboutRoute: typeof LegalAboutRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  MarketListingIdRoute: typeof MarketListingIdRoute
  MarketMyListingsRoute: typeof MarketMyListingsRoute
  SellerNameRoute: typeof SellerNameRoute
  CollectionIndexRoute: typeof CollectionIndexRoute
  MarketIndexRoute: typeof MarketIndexRoute
  MarketPublishScanIdRoute: typeof MarketPublishScanIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-history': {
      id: '/price-history'
      path: '/price-history'
      fullPath: '/price-history'
      preLoaderRoute: typeof PriceHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-scan': {
      id: '/first-scan'
      path: '/first-scan'
      fullPath: '/first-scan'
      preLoaderRoute: typeof FirstScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera-permissions': {
      id: '/camera-permissions'
      path: '/camera-permissions'
      fullPath: '/camera-permissions'
      preLoaderRoute: typeof CameraPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/': {
      id: '/market/'
      path: '/market'
      fullPath: '/market/'
      preLoaderRoute: typeof MarketIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/': {
      id: '/collection/'
      path: '/collection'
      fullPath: '/collection/'
      preLoaderRoute: typeof CollectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/$name': {
      id: '/seller/$name'
      path: '/seller/$name'
      fullPath: '/seller/$name'
      preLoaderRoute: typeof SellerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$threadId': {
      id: '/messages/$threadId'
      path: '/$threadId'
      fullPath: '/messages/$threadId'
      preLoaderRoute: typeof MessagesThreadIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/market/my-listings': {
      id: '/market/my-listings'
      path: '/market/my-listings'
      fullPath: '/market/my-listings'
      preLoaderRoute: typeof MarketMyListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/$listingId': {
      id: '/market/$listingId'
      path: '/market/$listingId'
      fullPath: '/market/$listingId'
      preLoaderRoute: typeof MarketListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/about': {
      id: '/legal/about'
      path: '/legal/about'
      fullPath: '/legal/about'
      preLoaderRoute: typeof LegalAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$id': {
      id: '/collection/$id'
      path: '/collection/$id'
      fullPath: '/collection/$id'
      preLoaderRoute: typeof CollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/failed': {
      id: '/checkout/failed'
      path: '/failed'
      fullPath: '/checkout/failed'
      preLoaderRoute: typeof CheckoutFailedRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/certificate/$scanId': {
      id: '/certificate/$scanId'
      path: '/certificate/$scanId'
      fullPath: '/certificate/$scanId'
      preLoaderRoute: typeof CertificateScanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/success/$scanId': {
      id: '/scan/success/$scanId'
      path: '/success/$scanId'
      fullPath: '/scan/success/$scanId'
      preLoaderRoute: typeof ScanSuccessScanIdRouteImport
      parentRoute: typeof ScanRoute
    }
    '/scan/result/$scanId': {
      id: '/scan/result/$scanId'
      path: '/result/$scanId'
      fullPath: '/scan/result/$scanId'
      preLoaderRoute: typeof ScanResultScanIdRouteImport
      parentRoute: typeof ScanRoute
    }
    '/scan/failed/$scanId': {
      id: '/scan/failed/$scanId'
      path: '/failed/$scanId'
      fullPath: '/scan/failed/$scanId'
      preLoaderRoute: typeof ScanFailedScanIdRouteImport
      parentRoute: typeof ScanRoute
    }
    '/market/publish/$scanId': {
      id: '/market/publish/$scanId'
      path: '/market/publish/$scanId'
      fullPath: '/market/publish/$scanId'
      preLoaderRoute: typeof MarketPublishScanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutFailedRoute: typeof CheckoutFailedRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutFailedRoute: CheckoutFailedRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface MessagesRouteChildren {
  MessagesThreadIdRoute: typeof MessagesThreadIdRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesThreadIdRoute: MessagesThreadIdRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

interface ScanRouteChildren {
  ScanFailedScanIdRoute: typeof ScanFailedScanIdRoute
  ScanResultScanIdRoute: typeof ScanResultScanIdRoute
  ScanSuccessScanIdRoute: typeof ScanSuccessScanIdRoute
}

const ScanRouteChildren: ScanRouteChildren = {
  ScanFailedScanIdRoute: ScanFailedScanIdRoute,
  ScanResultScanIdRoute: ScanResultScanIdRoute,
  ScanSuccessScanIdRoute: ScanSuccessScanIdRoute,
}

const ScanRouteWithChildren = ScanRoute._addFileChildren(ScanRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BillingRoute: BillingRoute,
  CameraPermissionsRoute: CameraPermissionsRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRoute,
  FavoritesRoute: FavoritesRoute,
  FirstScanRoute: FirstScanRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  OfflineRoute: OfflineRoute,
  OnboardingRoute: OnboardingRoute,
  PremiumRoute: PremiumRoute,
  PriceHistoryRoute: PriceHistoryRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScanRoute: ScanRouteWithChildren,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  WalletRoute: WalletRoute,
  CertificateScanIdRoute: CertificateScanIdRoute,
  CollectionIdRoute: CollectionIdRoute,
  LegalAboutRoute: LegalAboutRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  MarketListingIdRoute: MarketListingIdRoute,
  MarketMyListingsRoute: MarketMyListingsRoute,
  SellerNameRoute: SellerNameRoute,
  CollectionIndexRoute: CollectionIndexRoute,
  MarketIndexRoute: MarketIndexRoute,
  MarketPublishScanIdRoute: MarketPublishScanIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
